export const MOCK_TEAM_POSTS = [
  {
    id: 10,
    authorType: "ADMIN",
    authorName: "관리자",
    title: "투수 고스변 포지션 AI 추천 활용법 — 선발/중계/마무리 세팅...",
    likeCount: 0,
    commentCount: 0,
    viewCount: 1204,
    createdAt: "2026-01-14",
    tags: [{ code: "pitcher", name: "투수 공략" }],
    isPinned: false,
  },
  {
    id: 11,
    authorType: "ADMIN",
    authorName: "관리자",
    title: "컴프야 처음 시작하는 뉴비를 위한 팀 선택 팁 (스카우트 편)",
    likeCount: 0,
    commentCount: 0,
    viewCount: 876,
    createdAt: "2026-01-12",
    tags: [{ code: "newbie", name: "뉴비 가이드" }],
    isPinned: false,
  },
  {
    id: 12,
    authorType: "ADMIN",
    authorName: "관리자",
    title: "레전드 타자 스킬 조합 추천 — 시즌 초반 효율 극대화",
    likeCount: 0,
    commentCount: 0,
    viewCount: 643,
    createdAt: "2026-01-02",
    tags: [{ code: "skill", name: "스킬 조합" }],
    isPinned: false,
  },
]
