USE compyafun;

INSERT INTO player_skills
    (skill_code, name, grade, target)
VALUES ('L1', '슈퍼스타', 'LEGEND', 'PITCHER'),
       ('L2', '팔색조', 'LEGEND', 'PITCHER'),
       ('L3', '라이징패스트볼', 'LEGEND', 'PITCHER'),
       ('L4', '베테랑', 'LEGEND', 'PITCHER'),
       ('L5', '캡틴', 'LEGEND', 'PITCHER'),
       ('L6', '투혼', 'LEGEND', 'PITCHER'),
       ('L7', '닥터K', 'LEGEND', 'PITCHER'),

       ('P1', '각성', 'PLATINUM', 'PITCHER'),
       ('P2', '뒷심', 'PLATINUM', 'PITCHER'),
       ('P3', '끝판왕', 'PLATINUM', 'PITCHER'),
       ('P4', '자이언트킬러', 'PLATINUM', 'PITCHER'),
       ('P5', '이닝이터', 'PLATINUM', 'PITCHER'),
       ('P6', '언터처블', 'PLATINUM', 'PITCHER'),
       ('P7', '결정구', 'PLATINUM', 'PITCHER'),
       ('P8', '수호신', 'PLATINUM', 'PITCHER'),
       ('P9', '버닝', 'PLATINUM', 'PITCHER'),
       ('P10', '에이스', 'PLATINUM', 'PITCHER'),
       ('P11', '벌떼야구', 'PLATINUM', 'PITCHER'),
       ('P12', '결자해지', 'PLATINUM', 'PITCHER'),
       ('P13', '투지', 'PLATINUM', 'PITCHER'),

       ('H1', '승승장구', 'HERO', 'PITCHER'),
       ('H2', '컨트롤아티스트', 'HERO', 'PITCHER'),
       ('H3', '피칭머신', 'HERO', 'PITCHER'),
       ('H4', '마당쇠', 'HERO', 'PITCHER'),
       ('H5', '저격수', 'HERO', 'PITCHER'),
       ('H6', '전력투구', 'HERO', 'PITCHER'),
       ('H7', '해결사', 'HERO', 'PITCHER'),
       ('H8', '승부사', 'HERO', 'PITCHER'),
       ('H9', '클린업킬러', 'HERO', 'PITCHER'),
       ('H10', '파워피쳐', 'HERO', 'PITCHER'),
       ('H11', '국보투수', 'HERO', 'PITCHER'),
       ('H12', '셋업맨', 'HERO', 'PITCHER'),
       ('H13', '야전지휘', 'HERO', 'PITCHER'),

       ('N1', '견제왕', 'NORMAL', 'PITCHER'),
       ('N2', '위기극복', 'NORMAL', 'PITCHER'),
       ('N3', '얼음장', 'NORMAL', 'PITCHER'),
       ('N4', '돌부처', 'NORMAL', 'PITCHER'),
       ('N5', '광속투구', 'NORMAL', 'PITCHER'),
       ('N6', '평정심', 'NORMAL', 'PITCHER'),
       ('N7', '완급조절', 'NORMAL', 'PITCHER'),
       ('N8', '우타킬러', 'NORMAL', 'PITCHER'),
       ('N9', '좌타킬러', 'NORMAL', 'PITCHER'),
       ('N10', '마구연마', 'NORMAL', 'PITCHER'),
       ('N11', '강심장', 'NORMAL', 'PITCHER'),
       ('N12', '노련함', 'NORMAL', 'PITCHER'),
       ('N13', '강철체력', 'NORMAL', 'PITCHER'),

       ('L1', '핵심타자', 'LEGEND', 'HITTER'),
       ('L2', '위압감', 'LEGEND', 'HITTER'),
       ('L3', '베테랑', 'LEGEND', 'HITTER'),
       ('L4', '대포군단', 'LEGEND', 'HITTER'),
       ('L5', '타격의달인', 'LEGEND', 'HITTER'),
       ('L6', '슈퍼스타', 'LEGEND', 'HITTER'),
       ('L7', '캡틴', 'LEGEND', 'HITTER'),

       ('P1', '게스히터', 'PLATINUM', 'HITTER'),
       ('P2', '레전드', 'PLATINUM', 'HITTER'),
       ('P3', '리드오프', 'PLATINUM', 'HITTER'),
       ('P4', '배팅머신', 'PLATINUM', 'HITTER'),
       ('P5', '스프레이히터', 'PLATINUM', 'HITTER'),
       ('P6', '슬러거', 'PLATINUM', 'HITTER'),
       ('P7', '에이스킬러', 'PLATINUM', 'HITTER'),
       ('P8', '예지력', 'PLATINUM', 'HITTER'),
       ('P9', '주루도사', 'PLATINUM', 'HITTER'),
       ('P10', '카리스마', 'PLATINUM', 'HITTER'),
       ('P11', '클러치', 'PLATINUM', 'HITTER'),
       ('P12', '파워히터', 'PLATINUM', 'HITTER'),
       ('P13', '호타준족', 'PLATINUM', 'HITTER'),

       ('H1', '거포본능', 'HERO', 'HITTER'),
       ('H2', '블로킹', 'HERO', 'HITTER'),
       ('H3', '빅스윙', 'HERO', 'HITTER'),
       ('H4', '승부근성', 'HERO', 'HITTER'),
       ('H5', '어퍼스윙', 'HERO', 'HITTER'),
       ('H6', '역전의힘', 'HERO', 'HITTER'),
       ('H7', '정밀타격', 'HERO', 'HITTER'),
       ('H8', '참을성', 'HERO', 'HITTER'),
       ('H9', '탈진', 'HERO', 'HITTER'),
       ('H10', '테이블세터', 'HERO', 'HITTER'),
       ('H11', '풀스윙히터', 'HERO', 'HITTER'),
       ('H12', '하체단련', 'HERO', 'HITTER'),
       ('H13', '훈련중독', 'HERO', 'HITTER'),

       ('N1', '다운스윙', 'NORMAL', 'HITTER'),
       ('N2', '당겨치기', 'NORMAL', 'HITTER'),
       ('N3', '대타전문가', 'NORMAL', 'HITTER'),
       ('N4', '득점기계', 'NORMAL', 'HITTER'),
       ('N5', '매의눈', 'NORMAL', 'HITTER'),
       ('N6', '밀어치기', 'NORMAL', 'HITTER'),
       ('N7', '수비대장', 'NORMAL', 'HITTER'),
       ('N8', '우완킬러', 'NORMAL', 'HITTER'),
       ('N9', '정면승부', 'NORMAL', 'HITTER'),
       ('N10', '좌완킬러', 'NORMAL', 'HITTER'),
       ('N11', '직구킬러', 'NORMAL', 'HITTER'),
       ('N12', '집중력', 'NORMAL', 'HITTER'),
       ('N13', '초구공략', 'NORMAL', 'HITTER')
;


INSERT INTO teams (team_code, team_name, latest_team_id, city, start_year, end_year, emblem_url)
VALUES ('DOO', '두산 베어스', NULL, NULL, 1999, 2025, NULL),
       ('SAM', '삼성 라이온즈', NULL, NULL, 1982, 2025, NULL),
       ('HAN', '한화 이글스', NULL, NULL, 1994, 2025, NULL),
       ('LOT', '롯데 자이언츠', NULL, NULL, 1982, 2025, NULL),
       ('KIA', 'KIA 타이거즈', NULL, NULL, 2001, 2025, NULL),
       ('KIW', '키움 히어로즈', NULL, NULL, 2008, 2025, NULL),
       ('SSG', 'SSG 랜더스', NULL, NULL, 2021, 2025, NULL),
       ('LG', 'LG 트윈스', NULL, NULL, 1990, 2025, NULL),
       ('NC', 'NC 다이노스', NULL, NULL, 2013, 2025, NULL),
       ('KT', 'KT wiz', NULL, NULL, 2015, 2025, NULL),
       ('OB', 'OB 베어스', 1, NULL, 1982, 1998, NULL),
       ('MBC', 'MBC 청룡', 8, NULL, 1982, 1989, NULL),
       ('BIN', '빙그레 이글스', 3, NULL, 1986, 1993, NULL),
       ('SUP', '삼미 슈퍼스타즈', 16, NULL, 1982, 1984, NULL),
       ('HAE', '해태 타이거즈', 5, NULL, 1982, 2000, NULL),
       ('HYU', '현대 유니콘스', NULL, NULL, 1996, 2007, NULL),
       ('SSA', '쌍방울 레이더스', NULL, NULL, 1991, 1999, NULL),
       ('CHU', '청보 핀토스', 16, NULL, 1985, 1987, NULL),
       ('PAC', '태평양 돌핀스', 16, NULL, 1988, 1995, NULL),
       ('SK', 'SK 와이번스', 7, NULL, 2000, 2020, NULL)
;
